website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, session
from flask_login import login_user, login_required, logout_user, current_user
from . models import *
from . models import User, Course, UserCourse
from . import db
import json
import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    courses = Course.query.all()
    if request.method == 'POST':
        
        coursecode=request.form.get('coursecode')
        email=request.form.get('email')
        addremove=request.form.get('addremove')
    
        
        member = User.query.filter_by(email=email).first()
        course = Course.query.filter_by(coursecode=coursecode).first()
        if not course or not member:
            flash('coursecode or user does not exist', category='error')
            return redirect(url_for('views.home'))
        relation = UserCourse.query.filter_by(user_id=member.id, course_id=course.id).first()
        
        if not member:
            flash("user does not exist", category='error')
        elif not course:
            flash("course does not exist", category='error')
        elif addremove != 'remove' and addremove != 'add':
            flash("'remove' or 'add'", category='error')
        elif addremove == 'add':
            if relation:
                flash("member of class", category='error')
                return redirect(url_for('views.home'))
            member.courses.append(course)
            db.session.commit()
        elif addremove == 'remove':
            if not relation:
                flash("Not member of class", category='error')
                return redirect(url_for('views.home'))
            member.courses.remove(course)
            db.session.commit()
            
            
    return render_template("home.html", user=current_user, courses=courses)

@views.route('/student-home', methods=['GET', 'POST'])
@login_required
def studentHome():
    courses=current_user.courses
    relations = []
    for course in courses:
        relation = UserCourse.query.filter_by(course_id=course.id, user_id=current_user.id) 
        relations.append(relation)
    return render_template("studenthome.html", user=current_user, courses=courses, relations=relations)


@views.route('/teacher-home', methods = ['GET', 'POST'])
@login_required
def teacherHome():
    state = session.get('state')
    courses=current_user.courses
    students=[]
    relations=UserCourse.query.all()
    return render_template("teacherhome.html", user=current_user, courses=courses, relations=relations)
    
@views.route('/create-course', methods=['GET', 'POST'])
def createCourse():
    if request.method=='POST':
        coursecode = request.form.get('coursecode')
        coursename = request.form.get('coursename')
        course = Course.query.filter_by(coursecode=coursecode).first()
        if course:
            flash('Course exists', category='error')
        elif len(coursecode)!=5:
            flash('wrong course code format, must be 5 alphanumeric characters', category='error')
        elif len(coursename)<6:
            flash('course name too short', category='error')
        else:
            new_course=Course(coursecode=coursecode, coursename=coursename, status=False)
            db.session.add(new_course)
            db.session.commit()
            flash('Course created', category='success')
    
    return render_template("createCourse.html", user=current_user)

@views.route('/toggle/<int:currentcourse>', methods=['GET', 'POST'])
def toggle(currentcourse):
    courses=Course.query.all()
    for course in courses:
        if currentcourse == course.id:
            course.status = not course.status
            db.session.commit()
        else:
            course.status=False
            db.session.commit()
    current_course=Course.query.filter_by(id=currentcourse)
    while current_course.status == True:
        reader=SimpleMFRC22()
        id, text = reader.read
        activeuser=User.query.filter_by(firstName=text)
        currentrelation=User.query.filter_by(course_id=current_course.id, user_id=activeuser.id)
        currentrelation.attendance = currentrelalation.attendance + 1
    return redirect(url_for('views.teacherHome'))#this is your next task

'''
@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
    
    return jsonify({})
'''


'''
    if request.method == 'POST':
        note = request.form.get('note')
        if len(note) < 1:
            flash("Note is too short", category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added', category='success')
            
    
'''

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          
          {% if user.is_authenticated and user.role=="admin"%}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Create User</a>
          <a class="nav-item nav-link" id="createCourse" href="/create-course">Create Course</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% elif user.is_authenticated and user.role=="teacher" %}
          <a class="nav-item nav-link" id="home" href="/teacher-home">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% elif user.is_authenticated and user.role=="student"%}
          <a class="nav-item nav-link" id="studentHome" href="/student-home">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

website/templates/createCourse.html
{% extends 'base.html' %}
{% block title %}Create Course{% endblock %}
{% block content %} 
<form method = "POST">
    <h3 align="center">Create Course</h3>
    <div class="form-group">
        <label for="coursename">Course name</label>
        <input
          type="coursename"
          class="form-control"
          id="coursename"
          name="coursename"
          placeholder="Course name"
        />
    </div>
    <div class="form-group">
      <label for="coursecode">Course code</label>
      <input
        type="coursecode"
        class="form-control"
        id="coursecode"
        name="coursecode"
        placeholder="Course Code"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content%}
    <br />
    <form method="POST">
      <div class="form-group">
        <label for="email">email</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="email"
        />
      </div>
      <div class="form-group">
        <label for="coursecode">Coursecode</label>
        <input
          type="coursecode"
          class="form-control"
          id="coursecode"
          name="coursecode"
          placeholder="coursecode"
        />
      </div>
      <!--<div class="form-group">
        <label for="addremove">Add or Remove</label>
        <input
          type="addremove"
          class="form-control"
          id="addremove"
          name="addremove"
          placeholder="'add' or 'remove'"
        />
      </div>-->
      <div class="form-group">
        <label><input type="radio" name="addremove" value="add" checked>Add</label>
        <label><input type="radio" name="addremove" value="remove">Remove</label>
      </div>
      <div align="left">
        <br />
        <button type="submit" class="btn btn-primary">Apply</button>
      </div>
    </form>
    <br />
    <ul class="list-group list-group-flush" id="viewcourse">
      {% for course in courses %}
      <li class="list-group-item">
        <h3 align="left">{{ course.coursename }}</h3>
          <ul>
              {% for User in course.users %}
                  <li>{{ User.firstName }}</li>
              {% endfor %}
          </ul>
      </li>
    {% endfor %}
    </ul>
    <br />

{% endblock %}
  
<!--
      <h1 align="center">Notes</h1>
    <ul class="list-group list-group-flush" id="notes">
      {% for note in user.notes %}
      <li class="list-group-item">
        {{ note.data }}
        <button type="button" class="close" onClick="deleteNote({{ note.id }})">
          <span aria-hidden="true">&times;</span>
        </button>
      </li>
      {% endfor %}
    </ul>
    <form method="POST">
      <textarea name="note" id="note" class="form-control"></textarea>
      <br />
      <div align="center">
        <button type="submit" class="btn btn-primary">Add Note</button>
      </div>
    </form>
  -->

website/templates/login.html
{% extends "base.html" %}
{% block title %}Attendease Login{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %}Attendease Create User{% endblock %}
{% block content %} 
<form method = "POST">
    <h3 align="center">Create User</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
    </div>
    <div class="form-group">
      <label for="usertype">"teacher" or "student"</label>
      <input
        type="usertype"
        class="form-control"
        id="usertype"
        name="usertype"
        placeholder="Enter type"
      />
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
    </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
    </div>
    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock %}

website/templates/studenthome.html
{% extends 'base.html' %}   

{% block content %}
<br />
<h1>My Courses</h1>
<br />
<ul class="list-group list-group-flush" id="viewcourse">
    {% for course in courses %}
    <li class="list-group-item">
      <h3 align="left">{{ course.coursename }}</h3>
      {% for relation in relations %}
        {% if relation.course_id == course.id%}
          <h3 style="color:#ff0000" align="left" >{{ relation.attendance }}</h3>
        {% else %}
          <h3 style="color:#ff0000" align="left" >0</h3>
        {% endif %} 

      {% endfor %}
    </li>
    <br />
    {% endfor %}
</ul>
{% endblock %}

website/templates/teacherhome.html
{% extends 'base.html' %}   
{% block content %}
<br />
<h1>Courses</h1>
<br />
<ul class="list-group list-group-flush" id="viewcourse">
    {% for course in courses %}
    <li class="list-group-item">
      <h3 align="left"><b>{{ course.coursename }}</b></h3>
        <a href="{{ url_for('views.toggle', currentcourse=course.id)}}">
        {% if course.status == true %}
            <button>Stop</button>
        {% else %}
            <button>Start</button>
        {% endif %}
        </a>
        {% set students = course.users %}
        {% for student in students %}
            {%if student.role=='student'%}
                <h3 align="left" ><i>{{ student.firstName }}</i></h3>
                {%for relation in relations%}
                    {% if relation.user_id==student.id and relation.course_id==course.id %}
                        <h3 style="color:#00c220" align="left" ><i>{{ relation.attendance }}</i></h3>
                        <br />
                    {% endif %}
                {%endfor%}
            {%endif%}
        {% endfor %}
    </li>
    <br />
    {% endfor %}
</ul>
{% endblock %}